version: '3.7'
services:
  lambda-1:
    build: .
    ports:
      - "9000:8080"
    volumes:
      - ./lambdas/lambda-1:/var/task
    environment:
      - PROJECT_NAME
      - CGO_ENABLED=0
      - ENVIRONMENT
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SESSION_TOKEN
  dynamo-1:
    image: amazon/dynamodb-local
    container_name: dynamodb-1
    hostname: dynamo
    restart: always
    volumes:
      - ./test/dynamo:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"